Remove bin/ executables from gemspec
See https://bundler.io/blog/2015/03/20/moving-bins-to-exe.html

Here's a similar PR on another gem:
https://github.com/hexorx/countries/pull/571

If both gems, `countries` and `wisper`, get installed in the same setup,
they end up conflicting with eash other:

```sh
$ gem install cp8_cli
wisper's executable "console" conflicts with countries
Overwrite the executable? [yN]  N
ERROR:  Error installing cp8_cli:
        "console" from wisper conflicts with installed executable from
	countries
```